// <auto-generated />
namespace WebAPI_Learn.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContact));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091031460_Add-Contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
